---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.pingTimeout: 60000
elasticsearch.requestTimeout: 60000
elasticsearch.shardTimeout: 60000
elasticsearch.startupTimeout: 60000
elasticsearch.hosts: http://elasticsearch:9200
